# -*- coding: utf-8 -*-
from pathlib import Path
p = Path(r"e:\LTClaw2.0\LTclaw2.0\src\ltclaw_gy_x\game\config.py")
src = p.read_text(encoding="utf-8")

old1 = 'class UserGameConfig(BaseModel):\n    """\u7528\u6237\u6e38\u620f\u914d\u7f6e"""\n    my_role: Literal["maintainer", "consumer"] = Field(default="consumer", description="\u6211\u7684\u89d2\u8272")\n    svn_local_root: Union[str, None] = Field(default=None, description="\u672c\u5730SVN\u6839\u76ee\u5f55")\n    svn_username: Union[str, None] = Field(default=None, description="SVN\u7528\u6237\u540d")'
new1 = 'class UserGameConfig(BaseModel):\n    """\u7528\u6237\u6e38\u620f\u914d\u7f6e"""\n    my_role: Literal["maintainer", "consumer"] = Field(default="consumer", description="\u6211\u7684\u89d2\u8272")\n    svn_local_root: Union[str, None] = Field(default=None, description="\u672c\u5730SVN\u5de5\u4f5c\u526f\u672c\u6839\u76ee\u5f55")\n    svn_url: Union[str, None] = Field(default=None, description="SVN\u8fdc\u7aefURL")\n    svn_username: Union[str, None] = Field(default=None, description="SVN\u7528\u6237\u540d")\n    svn_password: Union[str, None] = Field(default=None, description="SVN\u5bc6\u7801(\u843d\u76d8\u52a0\u5bc6)")\n    svn_trust_cert: bool = Field(default=False, description="\u4fe1\u4efb\u81ea\u7b7e\u8bc1\u4e66")'
assert old1 in src, "b1"
src = src.replace(old1, new1, 1)

old2 = 'def load_user_config() -> UserGameConfig:\n    """\u52a0\u8f7d\u7528\u6237\u914d\u7f6e\uff0c\u4e0d\u5b58\u5728\u5219\u8fd4\u56de\u9ed8\u8ba4\u503c"""\n    config_path = get_user_config_path()\n    if not config_path.exists():\n        return UserGameConfig()\n    try:\n        with open(config_path, "r", encoding="utf-8") as f:\n            data = yaml.safe_load(f)\n        return UserGameConfig.model_validate(data or {})\n    except Exception:\n        return UserGameConfig()'
new2 = '_USER_SECRET_FIELDS: frozenset[str] = frozenset({"svn_password"})\n\n\ndef load_user_config() -> UserGameConfig:\n    """\u52a0\u8f7d\u7528\u6237\u914d\u7f6e\uff0c\u89e3\u5bc6\u654f\u611f\u5b57\u6bb5"""\n    config_path = get_user_config_path()\n    if not config_path.exists():\n        return UserGameConfig()\n    try:\n        with open(config_path, "r", encoding="utf-8") as f:\n            data = yaml.safe_load(f) or {}\n        try:\n            from ltclaw_gy_x.security.secret_store import decrypt_dict_fields\n            data = decrypt_dict_fields(dict(data), _USER_SECRET_FIELDS)\n        except Exception:\n            pass\n        return UserGameConfig.model_validate(data)\n    except Exception:\n        return UserGameConfig()'
assert old2 in src, "b2"
src = src.replace(old2, new2, 1)

old3 = 'def save_user_config(cfg: UserGameConfig) -> None:\n    """\u4fdd\u5b58\u7528\u6237\u914d\u7f6e\uff0c\u539f\u5b50\u5199\u5165"""\n    config_path = get_user_config_path()\n    config_path.parent.mkdir(parents=True, exist_ok=True)\n    with tempfile.NamedTemporaryFile(\n        mode="w",\n        encoding="utf-8",\n        dir=config_path.parent,\n        delete=False,\n        suffix=".tmp"\n    ) as tmp:\n        yaml.dump(\n            cfg.model_dump(exclude_defaults=False),\n            tmp,\n            allow_unicode=True,\n            default_flow_style=False,\n            sort_keys=True\n        )\n        tmp_path = tmp.name\n    Path(tmp_path).replace(config_path)'
new3 = 'def save_user_config(cfg: UserGameConfig) -> None:\n    """\u4fdd\u5b58\u7528\u6237\u914d\u7f6e\uff0c\u539f\u5b50\u5199\u5165\uff1b\u654f\u611f\u5b57\u6bb5\u52a0\u5bc6"""\n    config_path = get_user_config_path()\n    config_path.parent.mkdir(parents=True, exist_ok=True)\n    payload = cfg.model_dump(exclude_defaults=False)\n    try:\n        from ltclaw_gy_x.security.secret_store import encrypt_dict_fields\n        payload = encrypt_dict_fields(payload, _USER_SECRET_FIELDS)\n    except Exception:\n        pass\n    with tempfile.NamedTemporaryFile(\n        mode="w",\n        encoding="utf-8",\n        dir=config_path.parent,\n        delete=False,\n        suffix=".tmp"\n    ) as tmp:\n        yaml.dump(\n            payload,\n            tmp,\n            allow_unicode=True,\n            default_flow_style=False,\n            sort_keys=True\n        )\n        tmp_path = tmp.name\n    Path(tmp_path).replace(config_path)'
assert old3 in src, "b3"
src = src.replace(old3, new3, 1)
p.write_bytes(src.encode("utf-8"))
print("OK size=", len(src))